apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

# optional: um den Service nach aussen sichtbar zu machen:
# kubectl port-forward service/mongodb-service 27017:27017

# Verbindung aufbauen:
# mongo --host 127.0.0.1 --port 27017
