apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tinyweb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tinyweb-deployment
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50