apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tinyweb-hpa
  labels:
    app: tinyweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tinyweb-deployment
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
